<?php


class Model_Parse extends Model
{
    public function get_data()
    {
        return parent::get_data(); // TODO: Change the autogenerated stub
    }

    public function add_or_update($data){
        $id = $this->check_name_exists($data['title']);
        if(empty($id)){
            $this->db->run("INSERT INTO `articles` (`title`, `content`, `meta_title`, `meta_description`, `meta_keywords`, `create_time`) VALUES (:title, :content, :metaTitle, :metaDescription, :metaKeywords, NOW())", ['title'=>$data['title'], 'content'=>$data['text'], 'metaTitle'=>$data['metaTitle'], 'metaDescription'=>$data['metaDescription'], 'metaKeywords'=>$data['metaKeywords']]);
        }else{
            $this->db->run("UPDATE `articles` SET title=:title, content=:content, meta_title=:metaTitle, meta_description=:metaDescription, meta_keywords=:metaKeywords, update_time=NOW() WHERE id=:id",['title'=>$data['title'], 'content'=>$data['text'], 'metaTitle'=>$data['metaTitle'], 'metaDescription'=>$data['metaDescription'], 'metaKeywords'=>$data['metaKeywords'], 'id'=>$id['id']]);
        }

    }

    private function check_name_exists($name){
        return $this->db->getRow("SELECT `id` FROM articles WHERE title=:title",['title'=>$name]);

    }

}