<?php


class Model_Article extends Model
{
    public function get_data()
    {
        return parent::get_data(); // TODO: Change the autogenerated stub
    }

    public function get_article($id){
        try {
           return $this->db->getRow("SELECT * FROM `articles` WHERE id=:id",['id'=>$id]);
        }catch (PDOException $e){
           echo $e;
        }
    }
}